### ISSUE TITLE
Please consider changing the license from GPLv2-only to GPLv2 or any later version

### ISSUE THREAD

**Issue by dacmot** [SokolovPavel/helicopter#11]
Would you please consider changing the license from GPLv2-only to "GPLv2 or any later version"? Being GPLv2-only technically prevents it being included in GPLv3 code.

From, [Is GPLv3 compatible with GPLv2?](https://www.gnu.org/licenses/gpl-faq.en.html#v2v3Compatibility)

> No. Many requirements have changed from GPLv2 to GPLv3, which means that the precise requirement of GPLv2 is not present in GPLv3, and vice versa. For instance, the Termination conditions of GPLv3 are considerably more permissive than those of GPLv2, and thus different from the Termination conditions of GPLv2.

>  Due to these differences, the two licenses are not compatible: if you tried to combine code released under GPLv2 with code under GPLv3, you would violate section 6 of GPLv2.

> However, if code is released under GPL “version 2 or later,” that is compatible with GPLv3 because GPLv3 is one of the options it permits.

**Comment by dacmot** [comment]
Good point. I think it should be sufficient to reply to this thread saying "I'm ok with the license change from GPLv2-only to GPLv2 or any later version"

Reminds me, I should add a note about contributors in the readme.

**Comment by Lazerbeak12345** [comment]
Reposted (in a way) this to the forumn. Pavel's been active there within a year or so. https://forum.minetest.net/viewtopic.php?p=416902#p416902

**Comment by Lazerbeak12345** [comment]
Pavel was "Last active:Sat Jan 16, 2021 02:22"

**Comment by AntumDeluge** [comment]
I don't have any authority for changing license in this project. But I agree that GPL2 or later would be better for users that want to fork this project.

**Comment by dacmot** [comment]
Thanks @AntumDeluge. That statement is all that is needed from you.

I am not a laywer, so take this with some skepticism: as I understand it, as a contributor, you need to provide your approval to license changes... unless you publicly renounce any and all copyrights on your contributions.

**Comment by AntumDeluge** [comment]
GitHub lists me as a contributor because the developer/owner accepted a pull request from me. I am not a member of the project. @SokolovPavel currently is the only member (as far as I know) that can authorize a change to licensing.

**Comment by Lazerbeak12345** [comment]
Thanks!
