### ISSUE TITLE
Can you add a deterioration (wearout)?

### ISSUE THREAD

**Issue by amadin** [SokolovPavel/helicopter#5]
Can you add a deterioration (wearout) of helicopter or add a fuel? And I would like it to be protected against theft and any player can't put back helicopter into the inventory (player can't dig helicopter).
I can't find any way to ask so i write here.

**Comment by AntumDeluge** [comment]
There is a [new helicopter mod](https://forum.minetest.net/viewtopic.php?t=24613) based on this one that does all that.
